<a href="https://colab.research.google.com/github/amargauge26/Pandas_tfk/blob/main/daat_rehsshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np


In [2]:
np.random.seed(100)
df=pd.DataFrame({"Date":pd.Index(pd.date_range(start='2/2/2019',periods=3)).repeat(3),
             "Class":["1A","2B","3C","1A","2B","3C","1A","2B","3C"],
             "Numbers":np.random.randn(9)})

df['Numbers2'] = df['Numbers'] * 2

df

Date Class   Numbers  Numbers2
0 2019-02-02    1A -1.749765 -3.499531
1 2019-02-02    2B  0.342680  0.685361
2 2019-02-02    3C  1.153036  2.306072
3 2019-02-03    1A -0.252436 -0.504872
4 2019-02-03    2B  0.981321  1.962642
5 2019-02-03    3C  0.514219  1.028438
6 2019-02-04    1A  0.221180  0.442359
7 2019-02-04    2B -1.070043 -2.140087
8 2019-02-04    3C -0.189496 -0.378992

In [4]:
df.pivot(index = "Date",columns="Class",values="Numbers")

Class             1A        2B        3C
Date                                    
2019-02-02 -1.749765  0.342680  1.153036
2019-02-03 -0.252436  0.981321  0.514219
2019-02-04  0.221180 -1.070043 -0.189496

In [5]:
df.pivot(index='Date', columns='Class')

Numbers                      Numbers2                    
Class             1A        2B        3C        1A        2B        3C
Date                                                                  
2019-02-02 -1.749765  0.342680  1.153036 -3.499531  0.685361  2.306072
2019-02-03 -0.252436  0.981321  0.514219 -0.504872  1.962642  1.028438
2019-02-04  0.221180 -1.070043 -0.189496  0.442359 -2.140087 -0.378992

In [6]:
df.pivot(index='Date', columns='Class')["Numbers"].reset_index()

Class       Date        1A        2B        3C
0     2019-02-02 -1.749765  0.342680  1.153036
1     2019-02-03 -0.252436  0.981321  0.514219
2     2019-02-04  0.221180 -1.070043 -0.189496

In [7]:
df.pivot(index='Date', columns='Class')["Numbers"]

Class             1A        2B        3C
Date                                    
2019-02-02 -1.749765  0.342680  1.153036
2019-02-03 -0.252436  0.981321  0.514219
2019-02-04  0.221180 -1.070043 -0.189496

In [8]:
np.random.seed(100)
df1=pd.DataFrame({"Date":pd.Index(pd.date_range(start='2/2/2019',periods=3)).repeat(3),
             "Class":["1A","1A","1A","2B","2B","2B","3C","3C","3C"],
             "Numbers":np.random.randn(9)})

df1

Date Class   Numbers
0 2019-02-02    1A -1.749765
1 2019-02-02    1A  0.342680
2 2019-02-02    1A  1.153036
3 2019-02-03    2B -0.252436
4 2019-02-03    2B  0.981321
5 2019-02-03    2B  0.514219
6 2019-02-04    3C  0.221180
7 2019-02-04    3C -1.070043
8 2019-02-04    3C -0.189496

In [9]:
df1.pivot(index="Date",columns = "Class")

ValueError: Index contains duplicate entries, cannot reshape

In [10]:
df

Date Class   Numbers  Numbers2
0 2019-02-02    1A -1.749765 -3.499531
1 2019-02-02    2B  0.342680  0.685361
2 2019-02-02    3C  1.153036  2.306072
3 2019-02-03    1A -0.252436 -0.504872
4 2019-02-03    2B  0.981321  1.962642
5 2019-02-03    3C  0.514219  1.028438
6 2019-02-04    1A  0.221180  0.442359
7 2019-02-04    2B -1.070043 -2.140087
8 2019-02-04    3C -0.189496 -0.378992

In [12]:
df.melt(id_vars=['Date',"Class"])

Date Class  variable     value
0  2019-02-02    1A   Numbers -1.749765
1  2019-02-02    2B   Numbers  0.342680
2  2019-02-02    3C   Numbers  1.153036
3  2019-02-03    1A   Numbers -0.252436
4  2019-02-03    2B   Numbers  0.981321
5  2019-02-03    3C   Numbers  0.514219
6  2019-02-04    1A   Numbers  0.221180
7  2019-02-04    2B   Numbers -1.070043
8  2019-02-04    3C   Numbers -0.189496
9  2019-02-02    1A  Numbers2 -3.499531
10 2019-02-02    2B  Numbers2  0.685361
11 2019-02-02    3C  Numbers2  2.306072
12 2019-02-03    1A  Numbers2 -0.504872
13 2019-02-03    2B  Numbers2  1.962642
14 2019-02-03    3C  Numbers2  1.028438
15 2019-02-04    1A  Numbers2  0.442359
16 2019-02-04    2B  Numbers2 -2.140087
17 2019-02-04    3C  Numbers2 -0.378992

In [13]:
df.melt(id_vars=['Date','Class'],value_vars=['Numbers'])

Date Class variable     value
0 2019-02-02    1A  Numbers -1.749765
1 2019-02-02    2B  Numbers  0.342680
2 2019-02-02    3C  Numbers  1.153036
3 2019-02-03    1A  Numbers -0.252436
4 2019-02-03    2B  Numbers  0.981321
5 2019-02-03    3C  Numbers  0.514219
6 2019-02-04    1A  Numbers  0.221180
7 2019-02-04    2B  Numbers -1.070043
8 2019-02-04    3C  Numbers -0.189496

In [14]:
df.melt(id_vars=['Date','Class'],value_vars=['Numbers'],value_name="Numbers_Value",var_name="Num_Var")

Date Class  Num_Var  Numbers_Value
0 2019-02-02    1A  Numbers      -1.749765
1 2019-02-02    2B  Numbers       0.342680
2 2019-02-02    3C  Numbers       1.153036
3 2019-02-03    1A  Numbers      -0.252436
4 2019-02-03    2B  Numbers       0.981321
5 2019-02-03    3C  Numbers       0.514219
6 2019-02-04    1A  Numbers       0.221180
7 2019-02-04    2B  Numbers      -1.070043
8 2019-02-04    3C  Numbers      -0.189496

In [15]:
image = np.array([[[ 0.67826139,  0.29380381],
                     [ 0.90714982,  0.52835647],
                     [ 0.4215251 ,  0.45017551]],

                   [[ 0.92814219,  0.96677647],
                    [ 0.85304703,  0.52351845],
                    [ 0.19981397,  0.27417313]],

                   [[ 0.60659855,  0.00533165],
                    [ 0.10820313,  0.49978937],
                    [ 0.34144279,  0.94630077]]])

In [16]:
print(f'Image Matrix :\n{image}')
print("===========================")
print(f'Shape of the given matrix is :\n{image.shape}')

Image Matrix :
[[[0.67826139 0.29380381]
  [0.90714982 0.52835647]
  [0.4215251  0.45017551]]

 [[0.92814219 0.96677647]
  [0.85304703 0.52351845]
  [0.19981397 0.27417313]]

 [[0.60659855 0.00533165]
  [0.10820313 0.49978937]
  [0.34144279 0.94630077]]]
Shape of the given matrix is :
(3, 3, 2)


In [17]:
x=image.reshape(image.shape[0] * image.shape[1] * image.shape[2], 1)
print(x)

[[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]


In [18]:
a = image.reshape(18,1)
a

array([[0.67826139],
       [0.29380381],
       [0.90714982],
       [0.52835647],
       [0.4215251 ],
       [0.45017551],
       [0.92814219],
       [0.96677647],
       [0.85304703],
       [0.52351845],
       [0.19981397],
       [0.27417313],
       [0.60659855],
       [0.00533165],
       [0.10820313],
       [0.49978937],
       [0.34144279],
       [0.94630077]])

In [19]:
image*image

array([[[4.60038513e-01, 8.63206788e-02],
        [8.22920796e-01, 2.79160559e-01],
        [1.77683410e-01, 2.02657990e-01]],

       [[8.61447925e-01, 9.34656743e-01],
        [7.27689235e-01, 2.74071567e-01],
        [3.99256226e-02, 7.51709052e-02]],

       [[3.67961801e-01, 2.84264917e-05],
        [1.17079173e-02, 2.49789414e-01],
        [1.16583179e-01, 8.95485147e-01]]])

In [20]:
np.dot(a,a)

ValueError: shapes (18,1) and (18,1) not aligned: 1 (dim 1) != 18 (dim 0)

In [21]:
b = a.reshape(1,-1)
print(a.shape)
print(b.shape)

(18, 1)
(1, 18)


In [22]:
result = np.dot(a,b)
result.shape

(18, 18)

In [23]:
result

array([[4.60038513e-01, 1.99275781e-01, 6.15284698e-01, 3.58363794e-01,
        2.85904200e-01, 3.05336667e-01, 6.29523012e-01, 6.55727152e-01,
        5.78588864e-01, 3.55082352e-01, 1.35526101e-01, 1.85961048e-01,
        4.11432376e-01, 3.61625234e-03, 7.33900054e-02, 3.38987833e-01,
        2.31587461e-01, 6.41839276e-01],
       [1.99275781e-01, 8.63206788e-02, 2.66524073e-01, 1.55233144e-01,
        1.23845680e-01, 1.32263280e-01, 2.72691712e-01, 2.84042610e-01,
        2.50628468e-01, 1.53811715e-01, 5.87061057e-02, 8.05531102e-02,
        1.78220965e-01, 1.56645908e-03, 3.17904918e-02, 1.46840021e-01,
        1.00317193e-01, 2.78026772e-01],
       [6.15284698e-01, 2.66524073e-01, 8.22920796e-01, 4.79298477e-01,
        3.82386419e-01, 4.08376633e-01, 8.41964021e-01, 8.77011101e-01,
        7.73841460e-01, 4.74909668e-01, 1.81261207e-01, 2.48716106e-01,
        5.50275765e-01, 4.83660534e-03, 9.81564499e-02, 4.53383837e-01,
        3.09739765e-01, 8.58436573e-01],
       [3.583

In [24]:
res = result.reshape(18*18,1)
print(res)

[[4.60038513e-01]
 [1.99275781e-01]
 [6.15284698e-01]
 [3.58363794e-01]
 [2.85904200e-01]
 [3.05336667e-01]
 [6.29523012e-01]
 [6.55727152e-01]
 [5.78588864e-01]
 [3.55082352e-01]
 [1.35526101e-01]
 [1.85961048e-01]
 [4.11432376e-01]
 [3.61625234e-03]
 [7.33900054e-02]
 [3.38987833e-01]
 [2.31587461e-01]
 [6.41839276e-01]
 [1.99275781e-01]
 [8.63206788e-02]
 [2.66524073e-01]
 [1.55233144e-01]
 [1.23845680e-01]
 [1.32263280e-01]
 [2.72691712e-01]
 [2.84042610e-01]
 [2.50628468e-01]
 [1.53811715e-01]
 [5.87061057e-02]
 [8.05531102e-02]
 [1.78220965e-01]
 [1.56645908e-03]
 [3.17904918e-02]
 [1.46840021e-01]
 [1.00317193e-01]
 [2.78026772e-01]
 [6.15284698e-01]
 [2.66524073e-01]
 [8.22920796e-01]
 [4.79298477e-01]
 [3.82386419e-01]
 [4.08376633e-01]
 [8.41964021e-01]
 [8.77011101e-01]
 [7.73841460e-01]
 [4.74909668e-01]
 [1.81261207e-01]
 [2.48716106e-01]
 [5.50275765e-01]
 [4.83660534e-03]
 [9.81564499e-02]
 [4.53383837e-01]
 [3.09739765e-01]
 [8.58436573e-01]
 [3.58363794e-01]
 [1.552331

In [25]:
res = result.reshape(18*18,1)

In [26]:
res


array([[4.60038513e-01],
       [1.99275781e-01],
       [6.15284698e-01],
       [3.58363794e-01],
       [2.85904200e-01],
       [3.05336667e-01],
       [6.29523012e-01],
       [6.55727152e-01],
       [5.78588864e-01],
       [3.55082352e-01],
       [1.35526101e-01],
       [1.85961048e-01],
       [4.11432376e-01],
       [3.61625234e-03],
       [7.33900054e-02],
       [3.38987833e-01],
       [2.31587461e-01],
       [6.41839276e-01],
       [1.99275781e-01],
       [8.63206788e-02],
       [2.66524073e-01],
       [1.55233144e-01],
       [1.23845680e-01],
       [1.32263280e-01],
       [2.72691712e-01],
       [2.84042610e-01],
       [2.50628468e-01],
       [1.53811715e-01],
       [5.87061057e-02],
       [8.05531102e-02],
       [1.78220965e-01],
       [1.56645908e-03],
       [3.17904918e-02],
       [1.46840021e-01],
       [1.00317193e-01],
       [2.78026772e-01],
       [6.15284698e-01],
       [2.66524073e-01],
       [8.22920796e-01],
       [4.79298477e-01],
